# como não foi criado acesso para o postgres o proprio quarkus cria um container do banco de dados e cria o banco
quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.database.generation=drop-and-create

# Validação do JWT
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=https://example.com/issuer

# Para gerar token
smallrye.jwt.sign.key.location=privateKey.pem

# habilita a telemetria do banco
quarkus.datasource.jdbc.telemetry=true